export const GET_PRODUCTS = "GET_PRODUCTS"
export const PRODUCTS_PAGINATION = "PRODUCTS_PAGINATION"
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"
export const MOST_VALUED_FILTER ="MOST_VALUED_FILTER"